# For more information about each component, please read http://wiki.merbivore.com/faqs/merb_components
dependency "merb-action-args"
dependency "merb-assets"
dependency "merb-cache"
dependency "merb-helpers"
dependency "merb-mailer"
dependency "merb-slices"
dependency "merb-auth-core"
dependency "merb-auth-more"
dependency "merb-auth-slice-password"
dependency "merb-param-protection"
dependency "merb-exceptions"
 
dependency "dm-core"
dependency "dm-aggregates"
dependency "dm-migrations"
dependency "dm-timestamps"
dependency "dm-types"
dependency "dm-validations"
dependency "dm-is-paginated"

dependency "tzinfo"

gem "archive-tar-minitar"
require "archive/tar/minitar"